### ISSUE TITLE
Just a tiny bit of an update?

### ISSUE THREAD

**Issue by alliha** [bullno1/TouchJoy#1]
Heya! Saw this project when looking for an on-screen controller for my surface, and immediately cloned it. However, it seems to be a bit outdated and I cannot for the life of my build this in vs2017. I've tried installing different platform tools and SDKs to no avail. (also tried installing an old vs2013, but it seems to have disappeared after installation and didn't leave any platform tools for vs2017 to use...) 

Do you, or anyone for that matter, know how to make it build properly? Or possibly add an executable for download?

**Comment by bullno1** [comment]
Try using GENie to generate the solution: https://github.com/bkaradzic/genie

**Comment by alliha** [comment]
Yea, that's what I did. afaik the problem is in that it's a vs2013 solution being handled in vs2017, as most of the errors are regarding header-files for stdio and some other libraries.

**Comment by alliha** [comment]
Wait nevermind, somehow it works now? not really sure what I did that made it work, but oh well. Thanks for being here anyways!
